[tool.poetry]
name = "badi-oerlikon-occupancy-monitor"
version = "2.0.0"
description = "Real-time occupancy monitoring for Badi Oerlikon via WebSocket collection on Azure Functions."
authors = ["Robin <robin@worreby.ch>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
azure-functions = "*"
azure-storage-blob = ">=12.18.0"
websockets = ">=11.0.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"